version: "2"
services:
  calculationdb:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=calculationdb
      - MYSQL_USER=calculationdb
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
    links:
      - calculationdb
    depends_on:
      - calculationdb
    environment:
      - MYSQL_USER=calculationdb
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - PMA_HOST=calculationdb