version: "2"
services:
  net-platform:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: net-platform
    expose:
     - 80
     - 443
    ports:
      - "8888:80"
    volumes:
     - ./:/home/
